### ISSUE TITLE
Update Config File

### ISSUE THREAD

**Issue by zluckytraveler** [phin05/discord-rich-presence-plex#71]
It'd be great to see the config file updated to `YAML` format. `YAML` is much easier to learn, understand, and use, especially for novice users that are not familiar or comfortable with `JSON` formatting, and I suspect that this change would require very little work to implement.

</br>

Additionally, just a couple suggestion just to clean up the config file. 

1. There seems to be some variations with the use of Uppercase and Lowercase letters for entries, where only some have the first letter uppercased while others do not. Maybe a default format could be used instead, something like all lowercase with an underscore between words, which from what I have seen is how most `YAML` files are done. 

**Examples**
- `write_to_file:`
- `hide_total_time:`
- `imgur_client_id:`

</br>

2. There are two entries for `name:` under `servers:` that is used for both the Plex server name and account username. It'd be great to either have server information (servers, name, token) in its own section separate from `users:` or have it updated to something that varies between the two.

**Examples**
- `name:`
- `account_username:`

</br>

**YAML Config Example**

```yaml
config:
  logging:
    debug: true
    write_to_file: true
  display:
    hide_total_time: false
    use_remaining_time: false
    poster:
      enabled: true
      imgur_client_id: XXXXXXXXXXXXXX
  button 1:
    label: IMDb
    url: dynamic:imdb
  button 2:
    label: Youtube 
    url: https://youtube.com/channel/me
  servers:
    token: XXXXXXXXXXXXXX
    name: MY SERVER
  users:
    account_username: plexuser123
    listen_for_user: mom, dad
    white_listed_libraries: Movies, TV Shows
    black_listed_libraries: Music
```

**Comment by zluckytraveler** [comment]
Here's a full config file example in `YAML`

```yaml
config:
  logging:
    debug: true
    write_to_file: true
  display:
    hide_total_time: false
    use_remaining_time: false
    poster:
      enabled: true
      imgue_client_id: XXXXXXXXXXXXXX
  button 1:
    label: IMDb
    url: dynamic:imdb
  button 2:
    label: TMDB
    url: dynamic:tmdb
  servers:
    token: XXXXXXXXXXXXXX
    name: MY SERVER
  users:
    account_username: plexuser123
    listenForUser: mom, dad
    whitelistedLibraries: Movies, TV Shows
    blacklistedLibraries: Music
```
